#!/bin/bash

jvm_arguments+=(
  "--add-modules jdk.incubator.vector"
  "-XX:+ClassUnloadingWithConcurrentMark"
  "-XX:+UseShenandoahGC"
  "-XX:-DontCompileHugeMethods"
)

if [[ $MEMORY -lt 12 ]]; then
  echo "Use ShenandoahGC standard memory options"
  jvm_arguments+=(
   "--add-modules jdk.incubator.vector"
   "-XX:+ClassUnloadingWithConcurrentMark"
   "-XX:+UseShenandoahGC"
   "-XX:-DontCompileHugeMethods"
  )
else
  echo "Use ShenandoahGC Advanced memory options"
  jvm_arguments+=(
   "--add-modules jdk.incubator.vector"
   "-XX:+ClassUnloadingWithConcurrentMark"
   "-XX:+UseShenandoahGC"
   "-XX:-DontCompileHugeMethods"
  )
fi
